#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 07-Nov-2022 13:31:27
#--------------------------------------------------------------
site    <- "DSM"
yrs     <- 2022
db_root <- "d:/database_local"
fx_path <- "C:/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 5
pthDatabase    <- "d:/database_local"
pthBiometR     <- "C:/Biomet.net/R/database_functions"
pthLogFile     <- "d:/database_local/Calculation_Procedures/TraceAnalysis_ini/DSM/log/DSM_ThirdStageCleaning.log"
ini_path       <- "d:/database_local/Calculation_Procedures/TraceAnalysis_ini/DSM"
