REM ----------------------------------------------------------
REM  This file is automatically generated by Matlab function:
REM  runThirdStageCleaningREddyProc.m
REM  06-Nov-2022 11:45:03
REM ----------------------------------------------------------
"C:\Program Files\R\R-4.2.1\bin\Rscript.exe" "C:/Biomet.net/R/database_functions/Run_ThirdStage_REddyProc.R" "C:/Biomet.net/R/database_functions" "d:\database_local\Calculation_Procedures\TraceAnalysis_ini\DSM\log\DSM_setThirdStageCleaningParameters.R"  2> "d:/database_local/Calculation_Procedures/TraceAnalysis_ini/DSM/log/DSM_ThirdStageCleaning.log" 1>&2
