#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 07-Nov-2022 14:22:17
#--------------------------------------------------------------
site    <- "DSM"
yrs     <- 2022
db_root <- "p:/database"
fx_path <- "C:/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 1
pthDatabase    <- "p:/database"
pthBiometR     <- "C:/Biomet.net/R/database_functions"
pthLogFile     <- "p:/database/Calculation_Procedures/TraceAnalysis_ini/DSM/log/DSM_ThirdStageCleaning.log"
ini_path       <- "p:/database/Calculation_Procedures/TraceAnalysis_ini/DSM"
