#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 07-Nov-2022 14:45:52
#--------------------------------------------------------------
site    <- "RBM"
yrs     <- 2022
db_root <- "D:/database_local"
fx_path <- "C:/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 1
pthDatabase    <- "D:/database_local"
pthBiometR     <- "C:/Biomet.net/R/database_functions"
pthLogFile     <- "D:/database_local/Calculation_Procedures/TraceAnalysis_ini/RBM/log/RBM_ThirdStageCleaning.log"
ini_path       <- "D:/database_local/Calculation_Procedures/TraceAnalysis_ini/RBM"
